site_name: High Performance Computing
site_url: https://hpc.thecoatlessprofessor.com/
repo_url: https://github.com/coatless/hpc
repo_name: coatless/hpc
site_author: James Balamuta
site_description: >-
  Tips, tricks, and so much more on harnessing High Performance Computing in
  everyday work.

theme:
  name: material
  language: en
  palette:
    primary: blue
  font:
    text: Roboto
    code: Roboto Mono
  features:
#    - tabs
    - instant

google_analytics:
  - UA-38501058-9
  - auto

# Enable MathJax
# Detailed at: https://squidfunk.github.io/mkdocs-material/reference/mathjax/
extra_javascript:
  - assets/javascript/mathjax_config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Enable extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: docs
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Add social pages
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/axiomsofxyz
    - icon: fontawesome/brands/github
      link: https://github.com/coatless/

# Structure
nav:
  - Home: index.md
  - Overview of Cluster Computing: cluster-computing.md
  - Illinois Cluster Computing:
    - Possible Clusters: illinois-cluster.md
    - Request ICC access for Research: https://campuscluster.illinois.edu/new_forms/user_form.php
    - Request ICC access for Instruction: https://campuscluster.illinois.edu/new_forms/class_form.php
  - Software: cluster-software.md
  - Storage: cluster-storage.md
  - Setting up a work environment: cluster-setup.md
  - Job Templates:
    - Slurm:
      - Single Job using R: slurm/single-job-r.md
      - Array Jobs with R: slurm/array-jobs-r.md
      - Custom Array Job Creation with R: slurm/custom-array-jobs-creation-r.md
      - Common Jobs in Bash: slurm/bash-jobs.md
    - PBS:
      - Common Jobs in Bash: pbs/bash-jobs.md
      - Common Jobs in R: pbs/r-jobs.md
    - Remote Compute Jobs in R: r-remote-jobs.md
  - Advanced:
      - Job Statistics: slurm-job-information.md
      - Creating Custom modulefiles: creating-modulefiles.md
  - Appendix:
    - Book Development Guide: mkdocs.md
