# Single Independent R Job

```{r}
#| results: "asis"
#| echo: false
source("../_common.R")
```

Consider the need to obtain random numbers across a **single** sample size under a specific mean.

$$X_{N} = \mu + Z \sim \mathcal{N}_{N} \left( \mu, 1 \right)$$

## Sample Job Script

**sim_job.R**

```{r}
#| echo: false
#| results: "asis"
print_sh("scripts/sim_job.R")
```

Download a copy and run it on the cluster with:

``` bash
# Download a copy of the script onto the cluster
wget https://hpc.thecoatlessprofessor.com/slurm/scripts/sim_job.R

# Execute the script with parameter values
Rscript $HOME/sim_job.R --args 5 10
# [1]  9.006482 11.288477 11.109700 12.280027  9.500943
```

## Sample Slurm Submission File

**sim_single_launch.slurm**

```{r}
#| echo: false
#| results: "asis"
print_sh("scripts/sim_single_launch.slurm")
```

``` bash
# Download a copy of the script onto the cluster
wget https://hpc.thecoatlessprofessor.com/slurm/scripts/sim_single_launch.slurm

# Queue the job on the Cluster
sbatch sim_single_launch.slurm
```
